# Generated by Django 4.1.4 on 2022-12-28 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0003_welcome_speech_minister_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ca',
            name='scr',
            field=models.TextField(verbose_name='SCRIPTURE'),
        ),
        migrations.AlterField(
            model_name='pastor_desk',
            name='message',
            field=models.TextField(verbose_name='MESSAGE'),
        ),
        migrations.AlterField(
            model_name='prophet_focus',
            name='body',
            field=models.TextField(verbose_name='BODY'),
        ),
        migrations.AlterField(
            model_name='prophet_focus',
            name='book',
            field=models.TextField(verbose_name='BOOKS of THE Month'),
        ),
        migrations.AlterField(
            model_name='recommended_books',
            name='book_body',
            field=models.TextField(verbose_name='BOOK BODY'),
        ),
        migrations.AlterField(
            model_name='services',
            name='message',
            field=models.TextField(verbose_name='MESSAGES'),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='t_body',
            field=models.TextField(verbose_name='TESTIMONY'),
        ),
    ]
